# from turtle import Turtle,Screen
# timmy = Turtle()
# print(timmy)
# timmy.shape("turtle")
# timmy.color("cyan")
# my_screen=Screen()
# timmy.forward(100)
# timmy.left(100)
# timmy.forward(100)
# timmy.left(100)
# timmy.forward(100)
# timmy.left(100)
# timmy.forward(100)
# print(my_screen.canvheight)
# my_screen.exitonclick()
from prettytable import PrettyTable
table=PrettyTable()
table.add_column("pokemon",["Pikachu","Squirtel","charmander"])
table.add_column("Type",["Electric","Water","Fire"])
table.align="l"
print(table)
